PRINT_DEBUG = False
PRINT_SOME_INFO = False
PATH_SHORTENING = ""
IMPL_LIMIT = 200 # default = 200
PRINT_TO_TERMINAL = True
WRITE_TXT_RESULT_TO_FILE = True
WRITE_PKL_TO_FILE = True
COMPACT_RESULT = False